---
title: "Calculating IRRs Efficiently"
author: "ASRS"
date: "2/13/2020"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
library('AZASRS')
library('tidyverse')
library('kableExtra')

tbl_out = function(df, n = 10) {
  df %>%
    head(n) %>%
    kable() %>%
    kable_styling()
}
```


# Portfolio Level Data  

### Inception to Date
```{r}
calc_grouped_irrs(pm_fund_portfolio,
                  itd = TRUE) %>%
  tbl_out()
```

### 1 Year
```{r}
calc_grouped_irrs(pm_fund_portfolio,
                  start_date = '2018-06-30',
                  end_date = '2019-06-30') %>%
  tbl_out()
```

### Etc.

----

# Category Level Data  

### Inception to Date
```{r}
calc_grouped_irrs(pm_fund_portfolio, pm_fund_category_description,
                  itd = TRUE) %>%
  tbl_out()
```

### 1 Year
```{r}
calc_grouped_irrs(pm_fund_portfolio, pm_fund_category_description,
                  start_date = '2018-06-30',
                  end_date = '2019-06-30') %>%
  tbl_out()
```

### Etc.

----


# Fund Level Data  

### Inception to Date
```{r}
calc_grouped_irrs(pm_fund_portfolio, pm_fund_category_description, pm_fund_id,
                  itd = TRUE) %>%
  tbl_out()
```

### 1 Year
```{r}
calc_grouped_irrs(pm_fund_portfolio, pm_fund_category_description, pm_fund_id,
                  start_date = '2018-06-30',
                  end_date = '2019-06-30') %>%
  tbl_out()
```

### Etc.


----

# Trailing IRR's can be calculated similarly  

### 1 Year trailing - starting 2015-12-31

```{r}
build_grouped_irrs(pm_fund_portfolio,
                   start_date = '2015-12-31',
                   end_date = '2019-06-30',
                   n_qtrs = 4)  %>% # 4 = 1 year, 12 = 3 years, and so forth
  tbl_out()
```


#### Quarterly trailing
```{r}
build_grouped_irrs(pm_fund_portfolio, pm_fund_category_description,
                   start_date = '2015-12-31',
                   end_date = '2019-06-30',
                   n_qtrs = 1)  %>% # 4 = 1 year, 12 = 3 years, and so forth
  tbl_out()
```
