---
title: "Arizona State Retirement System  \n Private Equity Portfolio  \n Information compiled through 06/28/2019"

output: pdf_document
---

```{r, warning = FALSE, message = FALSE}
library(AZASRS)
library(tidyverse)
```


```{r}
value_date <- "2019-03-31"
```

```{r}
fund_info <- get_pm_fund_info()
cash_flow <- get_pm_cash_flow_daily()
nav_daily <- get_pm_nav_daily()
nav_cash_flow_combined <- build_nav_cash_flow_combined(pm_fund_description, pm_fund_portfolio, return_tibble=TRUE)
```


# Private Equity

```{r}
#first table
Private_equity_nav <- get_pm_nav_daily()%>%
  filter(pm_fund_portfolio == "PE", effective_date == value_date)%>%
  summarize("Beginning NAV" = sum(nav))


```



```{r}
#private equity long tables
Private_equity_info1 <- get_pm_fund_info()%>%
  filter(pm_fund_portfolio=="PE")%>%
  group_by(pm_fund_description)%>%
  summarize("Vintage Year" = min(vintage), "Committed" = round(sum(commit)/1e6))


Private_equity_cashflow <- get_pm_cash_flow_daily()%>%
  filter(pm_fund_portfolio=="PE", effective_date <= value_date)%>%
  group_by(pm_fund_description)%>%
  summarize("Called through 06/28/2019" = abs(round(sum(contributions)/1e6)), "Distributed through 06/28/2019" = round(sum(distributions)/1e6), "Unfunded as of 03/31/2019" = round(sum(unfunded)/1e6))


Private_equity <- Private_equity_info1%>%
  left_join(Private_equity_cashflow, by="pm_fund_description")

knitr::kable(Private_equity)


pe_nav <- get_pm_nav_daily()%>%
  filter(pm_fund_portfolio=="PE", effective_date == value_date)%>%
  group_by(pm_fund_description)%>%
  summarize(nav = nav)

pe_dpi <- get_pm_cash_flow_daily()%>%
  filter(pm_fund_portfolio=="PE", effective_date <= value_date)%>%
  group_by(pm_fund_description)%>%
  summarize("DPI" = calc_dpi(distributions, contributions)) #this works?



#trying to use build_nav_cash_flow_combined:
pe_dpi <- build_nav_cash_flow_combined(pm_fund_description, pm_fund_portfolio, return_tibble = TRUE)%>%
  filter(pm_fund_portfolio=="PE", effective_date <= value_date)%>%
  group_by(pm_fund_description)%>%
  summarize("DPI" = calc_dpi(distributions, contributions))



```


# Real Estate

```{r}
#real estate long tables
Real_estate_info1 <- get_pm_fund_info()%>%
  filter(pm_fund_portfolio=="RE")%>%
  group_by(pm_fund_description)%>%
  summarize("Vintage Year" = min(vintage), "Committed" = sum(commit))


Real_estate_cashflow <- get_pm_cash_flow_daily()%>%
  filter(pm_fund_portfolio=="RE", effective_date <= value_date)%>%
  group_by(pm_fund_description)%>%
  summarize("Called through 06/28/2019" = sum(contributions), "Distributed through 06/28/2019" = sum(distributions), "Unfunded as of 03/31/2019" = sum(unfunded))


Real_estate <- Real_estate_info1%>%
  left_join(Real_estate_cashflow, by="pm_fund_description")

knitr::kable(Real_estate)


RE_nav <- get_pm_nav_daily()%>%
  filter(pm_fund_portfolio=="RE", effective_date == value_date)%>%
  group_by(pm_fund_description)%>%
  summarize(nav = nav)


RE_dpi <- get_pm_cash_flow_daily()%>%
  filter(pm_fund_portfolio=="RE", effective_date <= value_date)%>%
  group_by(pm_fund_description)%>%
  summarize("DPI" = calc_dpi(distributions, contributions))
```



# Private Credit

```{r}
#private credit long tables
Credit_info1 <- get_pm_fund_info()%>%
  filter(pm_fund_portfolio=="Credit")%>%
  group_by(pm_fund_description)%>%
  summarize("Vintage Year" = min(vintage), "Committed" = sum(commit))


Credit_cashflow <- get_pm_cash_flow_daily()%>%
  filter(pm_fund_portfolio=="Credit", effective_date <= value_date)%>%
  group_by(pm_fund_description)%>%
  summarize("Called through 06/28/2019" = sum(contributions), "Distributed through 06/28/2019" = sum(distributions), "Unfunded as of 03/31/2019" = sum(unfunded))


Credit <-  Credit_info1%>%
  left_join(Credit_cashflow, by="pm_fund_description")

knitr::kable(Credit)


Credit_nav <- get_pm_nav_daily()%>%
  filter(pm_fund_portfolio=="Credit", effective_date == value_date)%>%
  group_by(pm_fund_description)%>%
  summarize(nav = nav)

Credit_dpi <- get_pm_cash_flow_daily()%>%
  filter(pm_fund_portfolio=="Credit", effective_date <= value_date)%>%
  group_by(pm_fund_description)%>%
  summarize("DPI" = calc_dpi(distributions, contributions))
```





