---
title: "All PM Metrics"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(AZASRS)
```


# Calculate Metrics

The first entry for the `build_grouped_pm_metrics` function is `...` - this is where you can insert the breakdown you'd like.

For example, to simply see by fund, you could use `build_grouped_pm_metrics(pm_fund_common_name)`

For inception to date, simply use `itd = TRUE`
```{r}
# ITD category metrics
con = AZASRS_DATABASE_CONNECTION()
df = build_grouped_pm_metrics(pm_fund_portfolio, pm_fund_category_description,
                              con = con,
                              itd = TRUE)
df
```


For any date range other than ITD, simply enter a start and end date.

```{r}
# Last quarter's portfolio metrics
value_date = get_value_date(con)
start_date = calc_add_qtrs(value_date, -1)

df = build_grouped_pm_metrics(pm_fund_portfolio,
                              con = con,
                              start_date = start_date,
                              end_date = value_date)
df
```


```{r}

```

