---
title: "IRR Reconciliation"
date: "11/13/2019"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('AZASRS')
library('purrr')
library('tidyverse')
library('lubridate')
options(scipen = 999)
```


```{r message = FALSE}
con = AZASRS::AZASRS_DATABASE_CONNECTION()
pmfi = get_pm_fund_info() # for aggregation purposes at the end
nav = get_pm_nav_daily() %>% 
  select(pm_fund_portfolio, pm_fund_category, pm_fund_id, effective_date, nav)
cash_flow = get_pm_cash_flow_daily() %>% 
  select(pm_fund_portfolio, pm_fund_category, pm_fund_id, effective_date, cash_flow)
```


```{r}
# Setup dates dataframe for data filtering
minimum_nav_date = min(nav$effective_date)
years_to_lag = c(0.25, 0.50, 1, 3, 5, 7, 10)

all_lagged_dates = tibble()
for(i in years_to_lag){
  lagged_dates = build_lagged_date_range_df(con = con, start_date = minimum_nav_date, n_qtrs = i*4) %>%
    mutate(years_lagged = i)
  all_lagged_dates = bind_rows(all_lagged_dates, lagged_dates)
}

all_lagged_dates = bind_rows(all_lagged_dates, tibble(start_date = as_date('1900-03-31'),
                                                      end_date = as_date(get_value_date()),
                                                      years_lagged = 100))
all_lagged_dates = all_lagged_dates %>%
  mutate(nav = list(nav), cash_flow = list(cash_flow))
```

```{r}
# Build function to merge NAV and CF
merge_nav_and_cf = function(start_date, end_date, nav, cash_flow){
  
  if(start_date > '1900-12-31'){
    # Non ITD NAV will only be counted if still open (both nav dates land), first nav converted to negative
    nav_first_last = nav %>%
      filter(nav != 0) %>%
      group_by(pm_fund_portfolio, pm_fund_category, pm_fund_id) %>%
      filter(effective_date == end_date | effective_date == start_date) %>%
      mutate(n = n()) %>%
      ungroup() %>%
      filter(n == 2) %>%
      select(-n) %>%
      mutate(nav = if_else(effective_date == start_date, -1*nav, nav)) %>%
      mutate(cash_flow = 0,
             data_type = 'NAV')
    
    # Cash flow includes start, does not include end
    cf_filtered = cash_flow %>%
      filter(cash_flow != 0) %>%
      filter(effective_date >= start_date, effective_date < end_date) %>%
      mutate(nav = 0,
             data_type = 'CF')
    
    combined_nav_cf = bind_rows(nav_first_last, cf_filtered) %>%
      group_by(pm_fund_portfolio, pm_fund_category, pm_fund_id, effective_date) %>%
      summarize(nav = sum(nav), cash_flow = sum(cash_flow)) %>%
      ungroup() %>%
      mutate(modified_cash_flows = nav + cash_flow) %>%
      mutate(contributions = if_else(modified_cash_flows < 0, modified_cash_flows, 0),
             distributions = if_else(modified_cash_flows > 0, modified_cash_flows, 0))
    
  } else{
    # ITD exists only during exact fund dates
    nav_first_last = nav %>%
      filter(nav != 0) %>%
      group_by(pm_fund_portfolio, pm_fund_category, pm_fund_id) %>%
      filter(effective_date == min(effective_date) | effective_date == max(effective_date)) %>%
      mutate(n = n()) %>%
      mutate(date_type = if_else(effective_date == min(effective_date), 'START', 'END')) %>%
      mutate(nav = if_else(date_type == 'START', -1*nav, nav)) %>%
      ungroup() %>%
      filter(n == 2) %>%
      select(-n) %>%
      mutate(cash_flow = 0,
             data_type = 'NAV')
    
    nav_dates = nav_first_last %>%
      select(pm_fund_portfolio, pm_fund_category, pm_fund_id, effective_date, date_type) %>%
      pivot_wider(names_from = date_type, values_from = effective_date)
    
    # Cash flow includes start, does not include end
    cf_filtered = cash_flow %>%
      left_join(nav_dates) %>%
      filter(effective_date >= START, effective_date < END) %>%
      mutate(nav = 0,
             data_type = 'CF') %>%
      select(-START, -END)
    
    combined_nav_cf = bind_rows(nav_first_last, cf_filtered) %>%
      group_by(pm_fund_portfolio, pm_fund_category, pm_fund_id, effective_date) %>%
      summarize(nav = sum(nav), cash_flow = sum(cash_flow)) %>%
      ungroup() %>%
      mutate(modified_cash_flows = nav + cash_flow) %>%
      mutate(contributions = if_else(modified_cash_flows < 0, modified_cash_flows, 0),
             distributions = if_else(modified_cash_flows > 0, modified_cash_flows, 0))
  }
  
  return(combined_nav_cf)
}

```


```{r}
# Mutate new column of tibble for NAV and Cash Flow
all_trailing_data = all_lagged_dates %>%
  mutate(nav_and_cash_flow = pmap(.l = list(start_date, end_date, nav, cash_flow), .f = merge_nav_and_cf)) %>%
  select(-nav, -cash_flow)
```


```{r}
Create 
```


```{r}
all_trailing_metrics = all_trailing
```


```{r}
end_date = '2019-09-30'
years_to_lag = c(0.25, 0.50, 1, 3, 5, 7)

all_possible_dates = filled_list_of_dates(start_date = '2004-03-31', end_date = get_value_date()) %>% rename(end_date = effective_date)


create_all_metrics = function(end_date){
  
  db_irr_prep = tibble(years = c(0, 0, 1, 3, 5, 7), qtrs = c(1, 2, 0, 0, 0, 0)) %>%
  mutate(end_date = end_date) %>%
  mutate(start_date = pmap(
    .l = list(end_date = end_date, years = years, qtrs = qtrs),
    .f = calc_previous_year_qtr
  )) %>%
  unnest(cols = c(start_date)) %>%
  mutate(itd = FALSE) %>%
  bind_rows(tibble(years=0, qtrs=0, end_date = end_date, start_date = as_date("1900-12-31"), itd = TRUE)) %>%
  mutate(end_date = as_date(end_date),
         con = list(con))

build_lagged_pm_metrics2 = function(start_date, end_date, itd, n_qtrs, con, years_back){
  build_lagged_pm_metrics(pm_fund_portfolio, pm_fund_category, pm_fund_id,
                          start_date = start_date, end_date = end_date, itd=itd,
                          n_qtrs = n_qtrs)
  }


db_metrics = db_irr_prep %>%
  mutate(n_qtrs = if_else(years == 0, qtrs, years * 4)) %>%
  mutate(metrics = pmap(
    .l = list(con, start_date = start_date, end_date = end_date, 
              n_qtrs = n_qtrs, itd = itd, years_back = years),
    .f = build_lagged_pm_metrics2
  )) %>%
select(metrics)

return(db_metrics)

}


all_trailing_metrics = all_possible_dates %>%
  mutate(metrics = map(.x = end_date, .f = create_all_metrics))
  
  

# 
# all_db_irrs = tibble()
# for(years_back in years_to_lag){
#   print(paste('Number of years looking back:', as.character(years_back)))
# 
#   if(years_back >= 1){
#     start_date = AZASRS::calc_previous_year_qtr(end_date = end_date, years = years_back)
#   } else {
#     start_date = AZASRS::calc_previous_year_qtr(end_date = end_date, qtrs = 4*years_back)
#   }
#   print(start_date)
# 
#   db_irrs = build_lagged_pm_metrics(pm_fund_portfolio, pm_fund_category, pm_fund_id,
#                                     start_date = start_date, end_date = end_date, itd=FALSE,
#                                     n_qtrs = years_back*4)
#   all_db_irrs = bind_rows(all_db_irrs, db_irrs)
# }
# 
# # Add ITD
# db_irrs_itd = build_lagged_pm_metrics(pm_fund_portfolio, pm_fund_category, pm_fund_id,
#                                   start_date = start_date, end_date = end_date, itd=TRUE,
#                                   n_qtrs = 4) %>%
#   filter(itd == TRUE)
# 
# all_db_irrs = bind_rows(all_db_irrs, db_irrs_itd)
# 
# all_db_irrs %>% head()
```


```{r}
data_directory = './reconciliation_data/'
cont = AzureStor::blob_container(Sys.getenv('ASRS_BLOB_PM_RECONCILIATION'), key = Sys.getenv('ASRS_BLOB_KEY'))
all_files = AzureStor::list_blobs(cont) %>% filter(!str_detect(name, '/'))
AzureStor::multidownload_blob(cont, '*.csv', data_directory, overwrite = TRUE)

csv_irrs_raw = tibble()
for(file in all_files$name){
  tmp = read_csv(paste0(data_directory, file)) 
  tmp = tmp %>%
    select(`Client Grouping 1`, `3 Months` = `3 Month IRR`, `6 Months` = `6 Month IRR`,
           `1 Year` = `1 Year IRR`, `3 Year` = `3 Year IRR`, `5 Year` = `5 Year IRR`, 
           `7 Year` = `7 Year IRR`, `10 Year` = `10 Year IRR`, `ITD` = `ITD IRR`) %>%
    drop_na(`Client Grouping 1`) %>%
    mutate_all(as.character)
  csv_irrs_raw = bind_rows(csv_irrs_raw, tmp)
}

remove_parenthesis = function(x){
  y = gsub('\\)', '', x)
  z = gsub('\\(', '-', y)
  as.numeric(z)
}
# remove parentheses
csv_irrs_ids = csv_irrs_raw %>% select(`Client Grouping 1`)
csv_irrs = csv_irrs_raw %>% 
  select(-`Client Grouping 1`) %>% 
  mutate_all(remove_parenthesis) %>% 
  bind_cols(csv_irrs_ids) %>%
  select(`Client Grouping 1`, everything())

csv_irrs %>% head()
```

```{r}
csv = csv_irrs %>% select(pm_fund_id = `Client Grouping 1`, irr_csv = ITD) %>% mutate(irr_csv = irr_csv/100)
csv
```


```{r}
db = db_irrs_itd %>% select(pm_fund_id, irr_db = irr)
db
```


```{r}
csv_db = csv %>% left_join(db) %>% mutate(diff = abs(irr_csv - irr_db))
csv_db
```

```{r}
csv_db_f = csv_db %>% filter(diff > 0.002)
csv_db_f
```


```{r}
con = AZASRS_DATABASE_CONNECTION()
nav_dates_prep = get_pm_nav_daily(con = con, return_tibble = FALSE) %>%
  #filter(nav != 0) %>%
  filter(effective_date <= end_date) %>%
  group_by(pm_fund_id) %>%
  summarize(first_nav_date = min(effective_date, na.rm = TRUE),
            last_nav_date = max(effective_date, na.rm = TRUE)) %>%
  ungroup() %>%
  as_tibble() %>%
  mutate(end_date = as_date(end_date)) %>%
  mutate(days_of_fund_life = as.integer(last_nav_date - first_nav_date),
         days_since_last_nav = as.integer(end_date - last_nav_date))

nav_firsts = get_pm_nav_daily(con = con, return_tibble = FALSE) %>%
  #filter(nav != 0) %>%
  group_by(pm_fund_id) %>%
  filter(effective_date == min(effective_date, na.rm = TRUE)) %>%
  ungroup() %>%
  select(pm_fund_id, first_nav = nav) %>%
  as_tibble()

nav_dates = nav_dates_prep %>% left_join(nav_firsts)

```



```{r}
irrs_database = all_db_irrs %>% 
  select(pm_fund_id, irr, lagged_period) %>% 
  mutate(irr = if_else(is.na(irr), 0, irr))

irrs_csv = csv_irrs %>% 
  rename(pm_fund_id = `Client Grouping 1`) %>%
  pivot_longer(-pm_fund_id, names_to = "lagged_period", values_to = 'irr') %>%
  mutate(irr = irr/100)


irrs_comparison_db = irrs_database %>%
  left_join(irrs_csv, by = c('pm_fund_id', 'lagged_period')) %>%
  mutate(diff = irr.x - irr.y) %>%
  arrange(-diff) %>%
  left_join(pmfi, by = 'pm_fund_id') %>%
  left_join(nav_dates, by = 'pm_fund_id')
  
irrs_comparison_csv = irrs_csv %>%
  left_join(irrs_database, by = c('pm_fund_id', 'lagged_period'))  %>%
  mutate(diff = irr.x - irr.y) %>%
  arrange(-diff) %>%
  left_join(pmfi, by = 'pm_fund_id') %>%
  left_join(nav_dates, by = 'pm_fund_id')

write_csv(irrs_comparison_db, 'irr_db_on_left.csv')
write_csv(irrs_comparison_csv, 'irr_csv_on_left.csv')
```


```{r}
summary(irrs_comparison_db$diff)
```


```{r}
summary(irrs_comparison_db$diff)
```


```{r}
irrs_comparison_db %>%
  ggplot(aes(x = diff, col = lagged_period, fill = lagged_period)) + 
  geom_histogram(alpha = 0.5, bins = 50) + 
  facet_wrap(~lagged_period, scales = 'free_y') + 
  theme(legend.position = 'none')
```



```{r}
irrs_comparison_csv %>%
  ggplot(aes(x = diff, col = lagged_period, fill = lagged_period)) + 
  geom_histogram(alpha = 0.5, bins = 50) + 
  facet_wrap(~lagged_period, scales = 'free_y') + 
  theme(legend.position = 'none')
```


```{r}
irrs_comparison_csv %>%
  filter(abs(diff) > 0.001) %>%
  #filter(days_of_fund_life != 0) %>% # Fund had no difference between start and end date
  #filter(days_since_last_nav != 0) %>% # Fund ended before end_date (non-zero nav date)
  filter(irr.x != 0) %>%
  #filter(irr.y != 0) %>%
  filter(lagged_period != 'ITD') %>%
  arrange(-abs(diff))
```


