---
title: "IRR Example"
author: "Scott Stoltzman"
date: "9/26/2019"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('AZASRS')
library('tidyverse')
library('lubridate')
```


Calculate any P2P IRR  

`start_date` and `end_date` can be the quarter end dates of any year you have data for.
```{r}
irrs = build_privm_p2p_irr(start_date = '2016-12-31', end_date = '2019-03-31')
head(irrs)
```

Group by any `grouping_type`:  
```{r}
irrs %>% select(grouping_type) %>% unique()
```

Spread data to see it in a nice view
```{r}
irrs %>%
  filter(grouping_type == 'pm_fund_portfolio') %>%
  spread(key = grouping_type, value = irr)
```

Easily generate dates to analyze
```{r}
ending_date = '2019-03-31'
# previous year
calc_previous_year_qtr(ending_date, years = 1, qtrs = 0)
```

```{r}
# previous quarter
calc_previous_year_qtr(ending_date, years = 0, qtrs = 1)
```

Easily create a lot of comparisons
```{r}
# one quarter back, then years 1, 3, 5, 7, 10
years_quarters = tibble(years    = c(0, 1, 3, 5, 7, 10), 
                       quarters = c(1, 0, 0, 0, 0, 0)) %>%
  mutate(end_date = as_date(ending_date),
         start_date = calc_previous_year_qtr(end_date, years, quarters))
years_quarters
```

Create IRRs for all dates
```{r}
years_quarters = tibble(years    = c(0, 1, 3, 5, 10), 
                       quarters  = c(1, 0, 0, 0, 0),
                       cool_name = c('one_quarter', 'one_year', 'three_year', 'five_year', 'ten_year')) %>%
  mutate(end_date = ending_date,
         start_date = calc_previous_year_qtr(ending_date, years, quarters))

final_data = list()
for(i in 1:nrow(years_quarters)){
  yq = years_quarters[i,]
  final_data[[i]] = build_privm_p2p_irr(yq$start_date, yq$end_date)
  final_data[[i]]$start_date = yq$start_date
  final_data[[i]]$end_date = yq$end_date
  final_data[[i]]$cool_name = yq$cool_name
}
final_tibble = bind_rows(final_data)
head(final_tibble)
```


Easy to use plotting 

```{r}
final_tibble %>%
  filter(grouping_type == 'pm_fund_portfolio') %>%
  ggplot(aes(x = cool_name, y = irr, fill = name)) +
  geom_col(position = 'dodge')
```



```{r}
final_tibble %>%
  filter(grouping_type == 'pm_fund_category_description') %>%
  ggplot(aes(x = cool_name, y = irr, fill = cool_name)) +
  geom_col(position = 'dodge') + 
  coord_flip() +
  facet_wrap(~name) + 
  theme(legend.position = 'bottom')
```
