---
title: "R Notebook"
output: html_notebook
---

```{r}
library('AZASRS')
library('tidyverse')
```

```{r}
valdate = value_date()
next_qtr = next_quarter()
```


```{r}
nav_daily = get_pm_nav_daily() %>%
  mutate(effective_date = as.Date(effective_date, format = '%Y-%m-%d')) %>%
  filter(effective_date > '1900-01-01')
cash_flow_daily = get_pm_cash_flow_daily() %>%
  mutate(effective_date = as.Date(effective_date, format = '%Y-%m-%d')) %>%
  filter(effective_date > '1900-01-01')
ssbt_composite_daily = ssbt_composite_bor_daily() %>%
  mutate(effective_date = as.Date(effective_date, format = '%Y-%m-%d')) %>%
  filter(effective_date > '1900-01-01')
pm_f_i = pm_fund_info()
```


```{r}
# should it be >= or > next_qtr?
# need to group by this??
contrib_distrib = cash_flow_daily %>%
  mutate(valdate = if_else(effective_date <= valdate, 'up_to', 'after')) %>%
  group_by(pm_fund_id, valdate) %>%
  summarize(contributions = -1*sum(contributions), distributions = -1*sum(distributions))
contrib_distrib
```

```{r}
# old method
# contrib_distrib1 = cash_flow_daily %>%
#   filter(effective_date <= valdate) %>%
#   group_by(pm_fund_portfolio) %>%
#   summarize(contributions = -1*sum(contributions), distributions = -1*sum(distributions)) %>% 
#   mutate(after_valdate = FALSE)
# 
# contrib_distrib2 = cash_flow_daily %>%
#   filter(effective_date > valdate) %>%
#   group_by(pm_fund_portfolio) %>%
#   summarize(contributions = -1*sum(contributions), distributions = -1*sum(distributions)) %>%
#   mutate(after_valdate = TRUE)
# 
# contrib_distrib = bind_rows(contrib_distrib1, contrib_distrib2)
```


```{r}
nav = nav_daily %>%
  filter(effective_date >= valdate) %>%
  mutate(valdate = if_else(effective_date > valdate, 'after', 'up_to')) %>%
  group_by(pm_fund_id, valdate) %>%
  summarize(nav = nav)

nav_cf = contrib_distrib %>%
  left_join(nav, by = c('pm_fund_id', 'valdate')) %>%
  arrange(pm_fund_id, valdate) %>%
  left_join(pm_f_i, by = 'pm_fund_id')
nav_cf[is.na(nav_cf)] = 0
nav_cf
```


```{r}
nav_cf_up_to = nav_cf %>%
  filter(valdate == 'up_to') %>%
  group_by(pm_fund_id) %>%
  summarize(contributions_up_to = sum(contributions),
            distributions_up_to = sum(distributions),
            nav_up_to = sum(nav))

nav_cf_after = nav_cf %>%
  mutate(nav = if_else(valdate == 'after' & nav == 0,
                sum(nav), nav)) %>%
  filter(valdate == 'after') %>%
  group_by(pm_fund_id) %>%
  summarize(contributions_after = sum(contributions),
            distributions_after = sum(distributions),
            nav_after = sum(nav))

nav_cf_joined = bind_rows(nav_cf_up_to, nav_cf_after)
nav_cf_joined[is.na(nav_cf_joined)] = 0
nav_cf_fund = nav_cf_joined %>%
  group_by(pm_fund_id) %>%
  summarize(contributions_up_to = sum(contributions_up_to),
            distributions_up_to = sum(distributions_up_to),
            contributions_after = sum(contributions_after),
            distributions_after = sum(distributions_after),
            nav_up_to = sum(nav_up_to),
            nav_after = sum(nav_after)) %>%
  left_join(pm_f_i, by = 'pm_fund_id')

nav_cf_portfolio_rollup = nav_cf_fund %>%
  group_by(pm_fund_portfolio) %>%
  summarize(contributions_up_to = sum(contributions_up_to),
            distributions_up_to = sum(distributions_up_to),
            contributions_after = sum(contributions_after),
            distributions_after = sum(distributions_after),
            nav_up_to = sum(nav_up_to),
            nav_after = sum(nav_after)) %>%
  mutate(unrealized_gain_loss_up_to = nav_up_to - distributions_up_to - contributions_up_to,
         unrealized_gain_loss_after = nav_after - distributions_after - contributions_after - nav_up_to)

```

```{r}
portfolio_name = 'PE'
nav_cf_portfolio_rollup_filtered = nav_cf_portfolio_rollup %>%
  filter(pm_fund_portfolio == portfolio_name) %>%
  gather(pm_fund_portfolio)

portfolio_up_to = tibble(metric = c('nav_start', 'contributions_up_to', 'distributions_up_to', 'unrealized_gain_loss_up_to', 'nav_up_to' )) %>%
  left_join(nav_cf_portfolio_rollup_filtered, by = c('metric' = 'pm_fund_portfolio')) %>%
  rename()
portfolio_up_to[is.na(portfolio_up_to)] = 0

portfolio_after = tibble(metric = c('nav_up_to', 'contributions_after', 'distributions_after', 'unrealized_gain_loss_after', 'nav_after' )) %>%
  left_join(nav_cf_portfolio_rollup_filtered, by = c('metric' = 'pm_fund_portfolio'))

portfolio_joined = bind_cols(portfolio_up_to, portfolio_after) %>%
  mutate('metric' = c('Beginning NAV', 'Contributions', 'Distributions', 'Unrealized Gain/Loss', 'Ending NAV')) %>%
  rename(Lockdown = value, Post_Lockdown = value1) %>%
  select(-metric1)
```










```{r}
#Percent of total fund
total_fund = ssbt_composite_daily %>%
  filter(ssbt_composite_id == 'ASRSA001',
         effective_date == valdate)
ending_navs = portfolio_joined %>% filter(metric == 'Ending NAV')

pct_of_total_fund = tibble(metric = 'percent-of_total_fund',
                             Lockdown = ending_navs$Lockdown/total_fund$ending_market_value,
                             Post_Lockdown = ending_navs$Post_Lockdown/total_fund$ending_market_value)

portfolio_joined = bind_rows(portfolio_joined, pct_of_total_fund)
```






```{r}
#Unfunded
unfunded = nav_daily %>%
  filter(effective_date <= valdate) %>%
  filter(pm_fund_portfolio == portfolio_name) %>%
  group_by(pm_fund_portfolio) %>%
  summarize(unfunded = sum(unfunded))
```




```{r}
# rolling 12s
rolling_12s = cash_flow_daily %>% 
  filter(effective_date >= (lubridate::today() - months(12))) %>%
  group_by(pm_fund_portfolio) %>%
  summarize(contributions = sum(contributions),
            distributions = sum(distributions), 
            net_cash_flow = contributions + distributions)

```



```{r}
contrib_distrib_chart = cash_flow_daily %>% 
  filter(pm_fund_portfolio == portfolio_name) %>%
  mutate(yr_qtr = as.Date(as.yearqtr(effective_date))) %>%
  group_by(yr_qtr) %>%
  summarize(contributions = sum(contributions),
            distributions = sum(distributions), 
            net_cash_flow = contributions + distributions) %>%
  gather(distrib_type, value, -yr_qtr)

ggplot(contrib_distrib_chart, aes(x=yr_qtr, y=value, col=distrib_type)) +
  geom_line()
```

