---
title: "Recon - Scott Version"
author: "Scott"
date: "February 22, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
library('tidyverse')
library('lubridate')
library('AZASRS')
library('compare')
```

```{r constants}
con = AZASRS_DATABASE_CONNECTION() # allows passing of database object for lazy querying
fytd.bgn <- ymd("2018-07-01")
fytd.end <- ymd("2018-09-30")

path.etl_check_data = "P:/IMD/2018 Database Project/Application Data/etl_check_data/"

save_test_data = function(df, filename){
  output_path = paste0(path.etl_check_data, filename, '.rda')
  save(df, file = output_path)
  }

load_test_data = function(filename){
  input_path = paste0(path.etl_check_data, filename, '.rda')
  load(input_path)
  }

# 'not in' function (opposite of %in%)
'%ni%' <- Negate('%in%')
```



```{r load_MYSS_data, message=FALSE, warning=FALSE}
daily.data.account = daily_data_account()
daily.data.composite = daily_data_composite()
monthly.data.account = monthly_data_account()
monthly.data.composite = monthly_data_composite()
  

daily.data = daily.data.account %>% rename(daily_return = account_daily_return) %>%
 bind_rows(daily.data.composite %>% 
             rename(daily_return = composite_daily_return)) %>%
 filter(effective_date >= fytd.bgn, effective_date <= fytd.end) %>%
 rename(Date = effective_date,
       b.mv = beginning_market_value,
       e.mv = ending_market_value,
       cf = net_cash_flow,
       r.day = daily_return,
       b.day = benchmark_daily_return) %>%
  select(Date, Name, ID, b.mv, e.mv, cf, r.day, b.day) %>%
  mutate(Date = ymd(Date, tz = "America/Los_Angeles"))


monthly.data = monthly.data.account %>% 
  rename(monthly_return = account_monthly_return,
         fiscal_ytd_return = account_fiscal_ytd_return) %>%
 bind_rows(monthly.data.composite %>% 
             rename(monthly_return = composite_monthly_return,
                    fiscal_ytd_return = composite_fiscal_ytd_return)) %>%
 filter(effective_date >= fytd.bgn, effective_date <= fytd.end) %>%
 rename(Date = effective_date,
       r.MTD = monthly_return,
       b.MTD = benchmark_monthly_return,
       r.FYTD = fiscal_ytd_return,
       b.FYTD = benchmark_fiscal_ytd_return) %>%
  select(Date, Name, ID, b.Name, r.MTD, b.MTD, r.FYTD, b.FYTD) %>%
  mutate(Date = ymd(Date, tz = "America/Los_Angeles"))
```


```{r check_daily_data}
## Checking
daily.data[is.na(daily.data)] = 0
daily.data.scott = daily.data
load_test_data('daily.data.kerry')

a1 = daily.data.scott %>% select(ID)
b1 = daily.data.kerry %>% select(ID)
comparison = anti_join(a1, b1)
bad_ids = comparison %>% select(ID) %>% unique() %>% pull()
print(paste("These IDs are not in common"), str(bad_ids))

a2 = daily.data.scott %>% filter(ID %ni% bad_ids)
b2 = daily.data.scott %>% filter(ID %ni% bad_ids)
daily.comparison = anti_join(a2, b2)
```
```{r}
print(daily.comparison)
```


```{r}
monthly.data[is.na(monthly.data)] = 0
monthly.data.scott = monthly.data
load_test_data('monthly.data.kerry')

a1 = monthly.data.scott %>% select(ID)
b1 = monthly.data.kerry %>% select(ID)
comparison = anti_join(a1, b1)
bad_ids = comparison %>% select(ID) %>% unique() %>% pull()
print(paste("These IDs are not in common"), str(bad_ids))

a2 = monthly.data.scott %>% filter(ID %ni% bad_ids)
b2 = monthly.data.scott %>% filter(ID %ni% bad_ids)
monthly.comparison = anti_join(a2, b2)
```



```{r}
monthly.comparison
```



```{r warning=FALSE}
comps = tbl_book_of_record_composite_daily(con)  %>%
  replace(is.na(.), 0) %>%
  group_by(ssbt_composite_info_id, effective_date) %>%
  summarize_if(is.numeric, sum)

accts = tbl_ssbt_composite_info_account_info(con) %>%
  left_join(tbl_book_of_record_account_daily(con), by = 'account_info_id') %>%
  replace(is.na(.), 0) %>%
  group_by(ssbt_composite_info_id, effective_date) %>%
  summarize_if(is.numeric, sum)

ca = comps %>%
  left_join(accts, by = c('ssbt_composite_info_id', 'effective_date'), suffix = c('.comps', '.accts')) %>%
  mutate(beginning_market_value_delta = (beginning_market_value.comps - beginning_market_value.accts),
         ending_market_value_delta = (ending_market_value.comps - ending_market_value.accts),
         net_cash_flow_delta = (net_cash_flow.comps - net_cash_flow.accts),
         daily_return_delta = (daily_return.comps - daily_return.accts)) %>%
  left_join(tbl_ssbt_composite_info(con) %>% 
              select(ssbt_composite_info_id, ssbt_composite_id, asset_class_id), 
            by = 'ssbt_composite_info_id') %>%
  left_join(tbl_asset_class(con), by = 'asset_class_id')
```

```{r}
ca
```

