---
title: "Reproducing Performance Recon V3"
author: "Scott"
date: "February 21, 2019"
output: pdf_document
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include=FALSE)
library(tidyverse)
library(lubridate)
library(AZASRS)
library(XLConnect)
library(readxl)
library(magrittr)
library(knitr)
library(rmarkdown)
library(tinytex)
library(stringi)
library(bookdown)
library(kableExtra)
library(formattable)
library("DBI")
options(scipen = 999)
#Toggle for writing data frames to the excel files
write_file <- TRUE
```

```{r global_file_locations, message=FALSE, warning=FALSE}
con = AZASRS_DATABASE_CONNECTION() # allows passing of database object for lazy querying
fytd.bgn <- ymd("2018-07-01")
fytd.end <- ymd("2018-09-30")

path.r.long <- "P:/IMD/IMD Vista/ASSET ALLOCATION REPORTS/R Scripts/Performance_Recon/MYSS Data/MYSS.data.xlsm"
path.tree <- "P:/IMD/2018 Database Project/MYSS Data/DB Mapping.xlsx"
path.excel <- "P:/IMD/IMD Vista/ASSET ALLOCATION REPORTS/R Scripts/Performance_Recon/Excel Files/"
path.rds <- "P:/IMD/IMD Vista/ASSET ALLOCATION REPORTS/R Scripts/Daily_Recon/RDS Files/"
```


```{r load_MYSS_data}
daily.data.account = tbl_book_of_record_account_daily(con) %>%
  left_join(tbl_account_info(con), by = 'account_info_id') %>%
  rename(benchmark_info_id = saa_benchmark_id, account_daily_return = daily_return) %>%
  select(account_info_id, effective_date, account_daily_return, beginning_market_value, ending_market_value, account_id, benchmark_info_id) %>%
  left_join(tbl_benchmark_daily_return(con), by = c('benchmark_info_id', 'effective_date')) %>% 
  rename(benchmark_daily_return = daily_return) %>%
  select(account_id, effective_date, beginning_market_value, ending_market_value, account_daily_return, benchmark_daily_return) %>% as_tibble()

daily.data.composite = tbl_book_of_record_composite_daily(con) %>%
  left_join(tbl_ssbt_composite_info(con), by = 'ssbt_composite_info_id') %>%
  rename(composite_daily_return = daily_return) %>%
  left_join(tbl_benchmark_daily_return(con), by = c('benchmark_info_id', 'effective_date')) %>%
  as_tibble()
  
 

daily.data = bind_rows(daily.data.composite, daily.data.account) %>%
  rename(Date = effective_date,
         b.mv = beginning_market_value,
         e.mv = ending_market_value,
         cf = net_cash_flow,
         r.day = daily_return) %>% 
  as_tibble()
a = daily.data %>% select(Date, ID, r.day)

daily.data <- read_excel(path.r.long, sheet = "10r.Daily.All.Accounts") %>% 
   mutate(
      Date = ymd(`Effective Date`, tz = "America/Los_Angeles"),
      ID = `Account ID`,
      b.mv = `Beginning Mkt Value`,
      e.mv = `Ending Market Value`,
      cf = `Net Cash Flow`,
      r.day = `1 Day` / 100,
      b.day = `1 Day(Benchmark)` / 100) %>%
   filter(Date >= fytd.bgn, Date <= fytd.end) %>%
   select(Date, Name, ID, b.mv, e.mv, cf, r.day, b.day) %>% 
   drop_na(b.mv)

monthly.data <- read_excel(path.r.long, sheet = "12r.MYSS.monthly") %>% 
   mutate(
      Date = `Effective Date`,
      ID = `Account ID`,
      b.Name = `Benchmark Name`,
      r.MTD = `1 Month` / 100,
      b.MTD = `1 Month(Benchmark)` / 100,
      r.FYTD = `Fiscal YTD` / 100,
      b.FYTD = `Fiscal YTD(Benchmark)` / 100) %>% 
   select(Date, Name, ID, b.Name, r.MTD, b.MTD, r.FYTD, b.FYTD)

month.bgn <- floor_date(max(parse_date_time2(monthly.data$Date, orders = "mdy")), "month")
month.end <- ceiling_date(max(parse_date_time2(monthly.data$Date, orders = "mdy")), "month") - 1

policy.tree <- read_excel(path.tree, sheet = "Policy Tree")

```
