on:
  push:
  pull_request:

name: pkgdown

jobs:
  env:
      # otherwise remotes::fun() errors cause the build to fail. Example: Unavailability of binaries
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
      # if you use bookdown or blogdown, replace "PKGDOWN" by the respective
      BUILD_PKGDOWN: ${{ matrix.config.pkgdown }}
      # macOS >= 10.15.4 linking
      SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
      # use GITHUB_TOKEN from GitHub to workaround rate limits in {remotes}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      ASRS_BLOB_KEY: ${{ secrets.ASRS_BLOB_KEY }}
      ASRS_DATABASE: ${{ secrets.ASRS_DATABASE }}
      ASRS_DATABASE_DEVELOPMENT: ${{ secrets.ASRS_DATABASE_DEVELOPMENT }}
      ASRS_FUNCTIONS_CODE: ${{ secrets.ASRS_FUNCTIONS_CODE }}
      PORT: ${{ secrets.PORT }}
      PWD: ${{ secrets.PWD }}
      SERVER: ${{ secrets.SERVER }}
      UID: ${{ secrets.UID }}
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          install.packages('remotes', type = 'source', repos='http://cran.us.r-project.org')
          install.packages('testthat', type = 'source', repos='http://cran.us.r-project.org')
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("pkgdown")
          testthat::test_dir('tests')
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .
