on:
  push:
    branches:
      - master
      - development
      - add_github_actions_support
  pull_request:
    branches:
      - master
      - development
      - add_github_actions_support

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      CRAN: ${{ matrix.config.cran }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      ASRS_BLOB_KEY: ${{ secrets.ASRS_BLOB_KEY }}
      ASRS_DATABASE: ${{ secrets.ASRS_DATABASE }}
      ASRS_DATABASE_DEVELOPMENT: ${{ secrets.ASRS_DATABASE_DEVELOPMENT }}
      ASRS_FUNCTIONS_CODE: ${{ secrets.ASRS_FUNCTIONS_CODE }}
      PORT: ${{ secrets.PORT }}
      PWD: ${{ secrets.PWD }}
      SERVER: ${{ secrets.SERVER }}
      UID: ${{ secrets.UID }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
